# Generated by Django 4.1.7 on 2023-10-03 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_docter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bokking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('p_email', models.EmailField(max_length=254)),
                ('p_phone', models.CharField(max_length=200)),
                ('booking_date', models.DateField()),
                ('bookedon', models.DateField(auto_now=True)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.docter')),
            ],
        ),
    ]
