# Generated by Django 4.1.7 on 2023-10-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bokking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bokking',
            new_name='Booking',
        ),
    ]
